name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage bandit ruff black

    - name: Wait for Postgres to be ready
      run: |
        until pg_isready -h postgres -p 5432; do
          echo "Waiting for postgres..."
          sleep 2
        done

    - name: Run tests with coverage
      env:
        DB_HOST: postgres
        DB_NAME: test_db
        DB_USER: test_user
        DB_PASSWORD: test_pass
        SECRET_KEY: 'test-secret-key'
        DEBUG: 'False'
      run: |
        coverage run manage.py test
        coverage report --fail-under=80

    - name: Run security checks
      run: bandit -r .

    - name: Run ruff
      run: ruff check .

    - name: Run black
      run: black --check .
